package ecommerce.main;
import java.util.List;

import ecommerce.com.Product;
import ecommerce.com.Rating;
import ecommerce.com.businesslogic.Service;
public class Main {
	public static void main(String args[]) {
		
		//id automaticllay generated by hibernte engine
		
		Service s = new Service();
	Product products = new Product();
//		//add product
		products.setColor("gold");
		products.setLaptopName("DELL");
		products.setModel("674652R");
		products.setScreensize("19 inches");
		products.setWeight("2 Kg");
		
	//	s.addProductDetails(products);
		
		
//		Product p = new Product();
//	      p.setColor("grey");
//		  p.setLaptopName("Acer");
//		  p.setModel("67483JFHR8");
//	      p.setScreensize("17 inches");
//		  p.setWeight("1.7 Kg");
		
		  
	//	get details by id
		Product product = s.getProductDetailsById(2);
		System.out.println("ScreenSize: " + product.getScreensize());
		System.out.println("LaptopName: " + product.getLaptopName());
		System.out.println("Color: " + product.getColor());
		System.out.println("Weight: " + product.getWeight());
		System.out.println("Model: " + product.getModel());
		
//		  
//		//list of all products
		List<Product> list =s.getListOfAllProductDetails();	
		for (Product lists : list) {
		System.out.println("screensize is: " + lists.getScreensize());
		System.out.println("laptopName is: " + lists.getLaptopName());
		System.out.println("Color: " + lists.getColor());
		System.out.println("Weight: " + lists.getWeight());
		System.out.println("model is: " + lists.getModel());
		}	
//		
		//update details by id
		Product p1= new Product();
	    p1.setColor("Rose Gold");
		p1.setLaptopName("ACER");
	    p1.setModel("HEYG7635");
		p1.setScreensize("16 inches");
		p1.setWeight("2.0 Kg");
		String name = p1.getLaptopName();
		String model=p1.getModel();
		System.out.println("Laptop Name and Model are updated!");
		System.out.println(name);
		System.out.println(model);
//	    
//	    //delete product details
		Product prod =s.findProductById(3);
		prod.getId();
		s.deleteProductRecordById(3);
		
		
		
	 
	    
	    //delete all product details
	   s.deleteAllProductDetails();
		String str = s.deleteAllProductDetails();
		System.out.println(str);
	
//
//
//
/////
//		// Add rating to product
		Rating r1 = new Rating();
		r1.setRating("9");
		r1.setNumberOfStars("5");
		s.AddRating(r1);
//
////		// get rating by id
		Rating r2 = s.getRatingById(1);
		System.out.println("Rating: " + r2.getRating());
		System.out.println("Number of Stars: " + r2.getNumberOfStars());

//		// list of details
		List<Rating> l1 = s.getListOfAllRating();
		for (Rating lists : l1) {
			System.out.println("Rating: " + r2.getRating());
			System.out.println("Number of Stars: " + r2.getNumberOfStars());

		}
////
////		// update rating
////
		Rating r3 = new Rating();
		r3.setRating("7");
		r3.setNumberOfStars("3");
		String rating = r3.getRating();
		String nofstars = r3.getNumberOfStars();
		System.out.println("rating and no of stars are updated!");
		System.out.println(rating);
		System.out.println(nofstars);

//		// delete rating
		Product rprod =s.findProductById(3);
		rprod.getId();
		s.deleteProductRecordById(3);
		
		//serve.deleteAllProductDetails();
		
//
//		// detele all
		s.deleteAllRatingDetails();
	}
}

